### PR TITLE
this update should fix #716 so that an empty function will not allow …

### LINKED ISSUE #716: exercises/concept/language-list/LanguageListTest.php testLanguageListCount incorrect
The current assertion will allow an empty function to pass.
This should be corrected to get the return from the function call and assert that return is equal to the length of the list provided.

### PR DESCRIPTION
**Pull request by kharris-tsc**
this update should fix #716 so that an empty function will not allow a pass

### CODE REVIEW

File: exercises/concept/language-list/LanguageListTest.php [hunk 1]
```diff
@@ -118,6 +118,17 @@ public function testGettingFirstDoesNotMutate()
...
     public function testLanguageListCount()
+    {
+        $language_list = language_list('c', 'cpp', 'php');
+        $languages_count = language_list_length($language_list);
+        $this->assertEquals(3, $languages_count);
+    }
+
+    /**
+     * @testdox when getting the language count, original is unchanged
+     * @task_id 7
```
Comment (mk-mxp) [inline exercises/concept/language-list/LanguageListTest.php:129]: This is part of the 6th task (see `.docs/instructions.md`). There is no 7, yet :smiley: 

```suggestion
     * @task_id 6
```

**Comment by kharris-tsc** [comment]
@mk-mxp this PR is ready for your final approval when time allows.
Thanks!

**Review by mk-mxp — CHANGES_REQUESTED** [review]
Thanks for contributing! I'll merge when the task number is fixed.

**Comment by kharris-tsc** [comment]
@mk-mxp I have resolved the task number mistake in commit a43aa3b17070a9340324871b41b0a56682036122 :)

**Review by mk-mxp — APPROVED** [review]
